In [1]:
import json
import pandas as pd
import os

In [2]:
def make_data(example, data_source):
    question = example.pop('problem').rstrip()
    answer = example.pop('answer')
    solution = example.pop('solution')

    instruction = "Please reason step by step, and put your final answer within \\boxed{}.\n"
    prompt = f"{question}\n\n{instruction}"
    solution_prompt = f"The reference solution is: {solution}"
    prompt_with_solution = f"{question}\n\n{solution_prompt}\n\n{instruction}"
    answer_prompt = f"The reference answer is: {answer}."
    prompt_with_answer = f"{question}\n\n{answer_prompt}\n\n{instruction}"
    prompt_with_both = f"{question}\n\n{solution_prompt}\\{answer_prompt}\n\n{instruction}"

    example_data = {
        "data_source": data_source,
        "prompt": [{
            "role": "user",
            "content": prompt
        }],
        "prompt_with_solution": [{
            "role": "user",
            "content": prompt_with_solution
        }],
        "prompt_with_answer": [{
            "role": "user",
            "content": prompt_with_answer
        }],
        "prompt_with_both": [{
            "role": "user",
            "content": prompt_with_both
        }],
        "ability": "math",
        "reward_model": {
            "style": "rule",
            "ground_truth": str(answer)
        },
    }
    return example_data


json_path = "/home/aiops/qiph/verl/data/deepscaler/deepscaler.json"

with open(json_path, "r") as f:
    data = json.load(f)

data_list = []
for example in data:
    data_list.append(make_data(example, "sanity_test_deepscaler"))

train_data = pd.DataFrame(data_list)
par_path = "/home/aiops/qiph/verl/data/deepscaler/deepscaler_v1.parquet"
train_data.to_parquet(par_path)

In [49]:
# par_path = "/home/aiops/qiph/verl/data/deepscaler/deepscaler.parquet"
df = pd.read_parquet(par_path)

df.head()

,data_source,prompt,prompt_with_solution,prompt_with_answer,ability,reward_model
0,sanity_test_deepscaler,[{'content': 'The operation $\otimes$ is defin...,[{'content': 'The operation $\otimes$ is defin...,[{'content': 'The operation $\otimes$ is defin...,math,"{'ground_truth': '-\frac{2}{3}', 'style': 'rule'}"
1,sanity_test_deepscaler,[{'content': 'Doug constructs a square window ...,[{'content': 'Doug constructs a square window ...,[{'content': 'Doug constructs a square window ...,math,"{'ground_truth': '26', 'style': 'rule'}"
2,sanity_test_deepscaler,[{'content': 'Let $P(x)$ be a polynomial of de...,[{'content': 'Let $P(x)$ be a polynomial of de...,[{'content': 'Let $P(x)$ be a polynomial of de...,math,"{'ground_truth': '1', 'style': 'rule'}"
3,sanity_test_deepscaler,[{'content': 'Let $f$ be the function defined ...,[{'content': 'Let $f$ be the function defined ...,[{'content': 'Let $f$ be the function defined ...,math,"{'ground_truth': '\frac{\sqrt{2}}{2}', 'style'..."
4,sanity_test_deepscaler,[{'content': 'At Euclid Middle School the math...,[{'content': 'At Euclid Middle School the math...,[{'content': 'At Euclid Middle School the math...,math,"{'ground_truth': '28', 'style': 'rule'}"

In [50]:
prompt = df["prompt"].iloc[0][0]["content"]
prompt_with_solution = df["prompt_with_solution"].iloc[0][0]["content"]
prompt_with_answer = df["prompt_with_answer"].iloc[0][0]["content"]

print(prompt)
print(prompt_with_solution)
print(prompt_with_answer)

The operation $\otimes$ is defined for all nonzero numbers by $a \otimes b = \frac{a^{2}}{b}$. Determine $[(1 \otimes 2) \otimes 3] - [1 \otimes (2 \otimes 3)]$.

Please reason step by step, and put your final answer within \boxed{}.

The operation $\otimes$ is defined for all nonzero numbers by $a \otimes b = \frac{a^{2}}{b}$. Determine $[(1 \otimes 2) \otimes 3] - [1 \otimes (2 \otimes 3)]$.

The reference solution is: 1. **Apply the operation $\otimes$ to the innermost parentheses first:**
   \[
   (1 \otimes 2) \otimes 3 = \left(\frac{1^2}{2}\right) \otimes 3 = \frac{1}{2} \otimes 3
   \]
   \[
   1 \otimes (2 \otimes 3) = 1 \otimes \left(\frac{2^2}{3}\right) = 1 \otimes \frac{4}{3}
   \]

2. **Calculate each part using the definition of $\otimes$:**
   \[
   \frac{1}{2} \otimes 3 = \frac{\left(\frac{1}{2}\right)^2}{3} = \frac{\frac{1}{4}}{3} = \frac{1}{12}
   \]
   \[
   1 \otimes \frac{4}{3} = \frac{1^2}{\frac{4}{3}} = \frac{1}{\frac{4}{3}} = \frac{3}{4}
   \]

3. **Subtract the two results:**
   \[
   \left(\frac{1}{12}\right) - \left(\frac{3}{4}\right) = \frac{1}{12} - \frac{9}{12} = -\frac{8}{12} = -\frac{2}{3}
   \]

4. **Conclude with the final answer:**
   \[
   \boxed{A}
   \]

Please reason step by step, and put your final answer within \boxed{}.

The operation $\otimes$ is defined for all nonzero numbers by $a \otimes b = \frac{a^{2}}{b}$. Determine $[(1 \otimes 2) \otimes 3] - [1 \otimes (2 \otimes 3)]$.

The reference answer is: -\frac{2}{3}.

Please reason step by step, and put your final answer within \boxed{}.

In [51]:
df.head()

,data_source,prompt,prompt_with_solution,prompt_with_answer,ability,reward_model
0,sanity_test_deepscaler,[{'content': 'The operation $\otimes$ is defin...,[{'content': 'The operation $\otimes$ is defin...,[{'content': 'The operation $\otimes$ is defin...,math,"{'ground_truth': '-\frac{2}{3}', 'style': 'rule'}"
1,sanity_test_deepscaler,[{'content': 'Doug constructs a square window ...,[{'content': 'Doug constructs a square window ...,[{'content': 'Doug constructs a square window ...,math,"{'ground_truth': '26', 'style': 'rule'}"
2,sanity_test_deepscaler,[{'content': 'Let $P(x)$ be a polynomial of de...,[{'content': 'Let $P(x)$ be a polynomial of de...,[{'content': 'Let $P(x)$ be a polynomial of de...,math,"{'ground_truth': '1', 'style': 'rule'}"
3,sanity_test_deepscaler,[{'content': 'Let $f$ be the function defined ...,[{'content': 'Let $f$ be the function defined ...,[{'content': 'Let $f$ be the function defined ...,math,"{'ground_truth': '\frac{\sqrt{2}}{2}', 'style'..."
4,sanity_test_deepscaler,[{'content': 'At Euclid Middle School the math...,[{'content': 'At Euclid Middle School the math...,[{'content': 'At Euclid Middle School the math...,math,"{'ground_truth': '28', 'style': 'rule'}"

In [ ]:
# bash
# for key in aime_2025 aime_2026 brumo_2025 hmmt_feb_2025 hmmt_nov_2025 hmmt_feb_2026; do hf download --repo-type dataset MathArena/$key --local-dir . && mv data $key ; done

In [ ]:

def make_data_hmmt(example, data_source):
    question = example.pop('problem').rstrip()
    answer = example.pop('answer')

    instruction = "Please reason step by step, and put your final answer within \\boxed{}.\n"
    prompt = f"{question}\n\n{instruction}"

    example_data = {
        "data_source": data_source,
        "prompt": [{
            "role": "user",
            "content": prompt
        }],
        "ability": "math",
        "reward_model": {
            "style": "rule",
            "ground_truth": str(answer)
        },
    }
    return example_data

# hmmt_key = "aime_2025"
for hmmt_key in ["aime_2025", "aime_2026", "brumo_2025", "hmmt_feb_2025", "hmmt_nov_2025", "hmmt_feb_2026"]:
    hmmt_path = f"/home/aiops/qiph/verl/data/deepscaler/{hmmt_key}/train-00000-of-00001.parquet"
    hmmt_data = pd.read_parquet(hmmt_path)

    hmmt_train = []
    for row in hmmt_data.to_dict(orient="records"):
        hmmt_train.append(make_data_hmmt(row, f"sanity_test_{hmmt_key}"))

    hmmt_train = pd.DataFrame(hmmt_train)
    print(len(hmmt_train))
    print(hmmt_train["prompt"].iloc[2][0]["content"])
    print(hmmt_train["reward_model"].iloc[2]["ground_truth"])
    print(hmmt_train["data_source"].iloc[2])
    print("-" * 50)

    # hmmt_train.head()

    hmmt_par_path = f"/home/aiops/qiph/verl/data/deepscaler/{hmmt_key}.parquet"
    hmmt_train.to_parquet(hmmt_par_path)

30
The 9 members of a baseball team went to an ice-cream parlor after their game. Each player had a singlescoop cone of chocolate, vanilla, or strawberry ice cream. At least one player chose each flavor, and the number of players who chose chocolate was greater than the number of players who chose vanilla, which was greater than the number of players who chose strawberry. Let $N$ be the number of different assignments of flavors to players that meet these conditions. Find the remainder when $N$ is divided by $1000.$

Please reason step by step, and put your final answer within \boxed{}.

16
sanity_test_aime_2025
--------------------------------------------------
30
A hemisphere with radius $200$ sits on top of a horizontal circular disk with radius $200,$ and the hemisphere and disk have the same center. Let $\mathcal T$ be the region of points P in the disk such that a sphere of radius $42$ can be placed on top of the disk at $P$ and lie completely inside the hemisphere. The area of $\mathcal T$ divided by the area of the disk is $\tfrac pq,$ where $p$ and $q$ are relatively prime positive integers. Find $p+q.$

Please reason step by step, and put your final answer within \boxed{}.

79
sanity_test_aime_2026
--------------------------------------------------
30
Let $A, B, C, D$, and $E$ be five equally spaced points on a line in that order. Let $F, G, H$, and $I$ all be on the same side of line $A E$ such that triangles $A F B, B G C, C H D$, and $D I E$ are equilateral with side length $1$. Let $S$ be the region consisting of the interiors of all four triangles. Compute the length of segment $A I$ that is contained in $S$.

Please reason step by step, and put your final answer within \boxed{}.

\frac{\sqrt{13}}{2}
sanity_test_brumo_2025
--------------------------------------------------
30
Given that $x, y$, and $z$ are positive real numbers such that

$$
x^{\log _{2}(y z)}=2^{8} \cdot 3^{4}, \quad y^{\log _{2}(z x)}=2^{9} \cdot 3^{6}, \quad \text { and } \quad z^{\log _{2}(x y)}=2^{5} \cdot 3^{10}
$$
compute the smallest possible value of $x y z$.

Please reason step by step, and put your final answer within \boxed{}.

\frac{1}{576}
sanity_test_hmmt_feb_2025
--------------------------------------------------
30
Ashley fills each cell of a $3 \times 3$ grid with some of the numbers $1,2,3,$ and $4$ (possibly none or several).
Compute the number of ways she can do so such that each row and each column contains each of $1,2,3,$ and $4$ exactly once. (One such grid is shown below.)
\[
\begin{array}{cccc}
1 2 & 3 4 & \\
4 & 1 & 2 3 \\
3 & 2 & 1 4
\end{array}
\]

Please reason step by step, and put your final answer within \boxed{}.

1296
sanity_test_hmmt_nov_2025
--------------------------------------------------
33
Compute the sum of all positive integers \( n \) such that \( n \) has at least 6 positive integer divisors and the 6th largest divisor of \( n \) is 6.

Please reason step by step, and put your final answer within \boxed{}.

48
sanity_test_hmmt_feb_2026
--------------------------------------------------