In [3]:
import pandas as pd

# df = pd.read_parquet('/home/aiops/qiph/verl/data/dapo/dapo-math-17k.parquet')
# df = pd.read_parquet('/home/aiops/qiph/verl/data/dapo_filter/aime-2024-boxed.parquet')
data_path = "/home/aiops/qiph/deepscaler/data/train.parquet"
df = pd.read_parquet(data_path)

print(len(df))

print(df["prompt"].iloc[0])

df.head()

# df["data_source"] = "math_dapo_aime_2025"
# df.to_parquet('/home/aiops/qiph/verl/data/dapo/aime-2025.parquet')

40315
[{'content': 'The operation $\\otimes$ is defined for all nonzero numbers by $a \\otimes b = \\frac{a^{2}}{b}$. Determine $[(1 \\otimes 2) \\otimes 3] - [1 \\otimes (2 \\otimes 3)]$. Please reason step by step, and put your final answer within \\boxed{}.\n', 'role': 'user'}]

,data_source,prompt,ability,reward_model,extra_info
0,,[{'content': 'The operation $\otimes$ is defin...,math,"{'ground_truth': '-\frac{2}{3}', 'style': 'rule'}","{'index': 0, 'split': 'train'}"
1,,[{'content': 'Doug constructs a square window ...,math,"{'ground_truth': '26', 'style': 'rule'}","{'index': 1, 'split': 'train'}"
2,,[{'content': 'Let $P(x)$ be a polynomial of de...,math,"{'ground_truth': '1', 'style': 'rule'}","{'index': 2, 'split': 'train'}"
3,,[{'content': 'Let $f$ be the function defined ...,math,"{'ground_truth': '\frac{\sqrt{2}}{2}', 'style'...","{'index': 3, 'split': 'train'}"
4,,[{'content': 'At Euclid Middle School the math...,math,"{'ground_truth': '28', 'style': 'rule'}","{'index': 4, 'split': 'train'}"

In [ ]:
import pandas as pd

df = pd.read_parquet('/home/aiops/qiph/verl/data/sanity_test/aime_2025.parquet')

# df["data_source"] = "sanity_test_aime_2025"


print(len(df))

print(df["prompt"].iloc[0])

df.head()

# df.to_parquet('/home/aiops/qiph/verl/data/sanity_test/aime_2025.parquet')

30
[{'content': 'Find the sum of all integer bases $b>9$ for which $17_{b}$ is a divisor of $97_{b}$. Please reason step by step, and put your final answer within \\boxed{}.\n', 'role': 'user'}]

In [28]:
import torch

def compute_binary_kl(_p, _q):
    _eps = 1e-6
    p = torch.clamp(_p, min=_eps, max=1.0 - _eps)
    q = torch.clamp(_q, min=_eps, max=1.0 - _eps)
    print(p.dtype, q.dtype, p, q, (1 - p) / (1 - q), torch.log((1 - p) / (1 - q)), "|", p / q, torch.log(p / q))
    print(p * torch.log(p / q), (1 - p) * torch.log((1 - p) / (1 - q)))
    return p * torch.log(p / q) + (1 - p) * torch.log((1 - p) / (1 - q))

pp = torch.Tensor([1.0])
qq = torch.Tensor([0.0])
print(compute_binary_kl(pp, qq))
print(compute_binary_kl(qq, pp))

torch.float32 torch.float32 tensor([1.0000]) tensor([1.0000e-06]) tensor([1.0133e-06]) tensor([-13.8023]) | tensor([999999.]) tensor([13.8155])
tensor([13.8155]) tensor([-1.3986e-05])
tensor([13.8155])
torch.float32 torch.float32 tensor([1.0000e-06]) tensor([1.0000]) tensor([986894.0625]) tensor([13.8023]) | tensor([1.0000e-06]) tensor([-13.8155])
tensor([-1.3816e-05]) tensor([13.8023])
tensor([13.8023])

In [34]:
import pandas as pd

df = pd.read_parquet('/home/aiops/qiph/verl/data/sanity_test/aime_2025.parquet')

# MATH_TEST_FILE=${TEST_FILE:-"[${DATA_ROOT}/data/sanity_test/aime_2024.parquet,${DATA_ROOT}/data/sanity_test/aime_2025.parquet]"}

print(len(df))

print(df["prompt"].iloc[0])
print(df["prompt_critic"].iloc[0])
print('-' * 100)

prompt = df["prompt"].iloc[0][0]["content"]
answer = df["reward_model"].iloc[0]["ground_truth"]

print(prompt)
# print(prompt[:-71])
# print(prompt[-71:])
print(answer)

prompt_critic = f"{prompt}\n\nThe expected answer is {answer}. Please provide the detailed reasoning steps that lead to this answer."

print('-' * 50)
print(prompt_critic)

df.head()

# df["data_source"] = "math_dapo_aime_2025"
# df.to_parquet('/home/aiops/qiph/verl/data/dapo/aime-2025.parquet')

30
[{'content': 'Find the sum of all integer bases $b>9$ for which $17_{b}$ is a divisor of $97_{b}$. Please reason step by step, and put your final answer within \\boxed{}.\n', 'role': 'user'}]
[{'content': 'Find the sum of all integer bases $b>9$ for which $17_{b}$ is a divisor of $97_{b}$. Please reason step by step, and put your final answer within \\boxed{}.\n\nThe expected answer is 70. Please provide the detailed reasoning steps that lead to this answer.\n', 'role': 'user'}]
----------------------------------------------------------------------------------------------------
Find the sum of all integer bases $b>9$ for which $17_{b}$ is a divisor of $97_{b}$. Please reason step by step, and put your final answer within \boxed{}.

70
--------------------------------------------------
Find the sum of all integer bases $b>9$ for which $17_{b}$ is a divisor of $97_{b}$. Please reason step by step, and put your final answer within \boxed{}.


The expected answer is 70. Please provide the detailed reasoning steps that lead to this answer.

,data_source,prompt,ability,reward_model,response,is_correct,extra_info,prompt_critic
0,sanity_test_aime_2025,[{'content': 'Find the sum of all integer base...,math,"{'ground_truth': '70', 'style': 'rule'}",,False,"{'index': 0, 'split': 'test'}",[{'content': 'Find the sum of all integer base...
1,sanity_test_aime_2025,"[{'content': 'On $\triangle ABC$ points $A,D,E...",math,"{'ground_truth': '588', 'style': 'rule'}",,False,"{'index': 1, 'split': 'test'}","[{'content': 'On $\triangle ABC$ points $A,D,E..."
2,sanity_test_aime_2025,[{'content': 'The 9 members of a baseball team...,math,"{'ground_truth': '16', 'style': 'rule'}",,False,"{'index': 2, 'split': 'test'}",[{'content': 'The 9 members of a baseball team...
3,sanity_test_aime_2025,[{'content': 'Find the number of ordered pairs...,math,"{'ground_truth': '117', 'style': 'rule'}",,False,"{'index': 3, 'split': 'test'}",[{'content': 'Find the number of ordered pairs...
4,sanity_test_aime_2025,[{'content': 'There are $8!=40320$ eight-digit...,math,"{'ground_truth': '279', 'style': 'rule'}",,False,"{'index': 4, 'split': 'test'}",[{'content': 'There are $8!=40320$ eight-digit...

In [ ]:
import pandas as pd

def make_prompt_critic(row):
    content = row["prompt"][0]["content"]
    answer = row["reward_model"]["ground_truth"]
    critic_content = f"{content}\nThe reference answer is {answer}. Please provide the detailed reasoning steps that lead to this answer.\n"
    return [{"role": "user", "content": critic_content}]


# out_path = '/home/aiops/qiph/verl/data/sanity_test/aime_2025.parquet'
out_path = '/home/aiops/qiph/verl/data/dapo/dapo-math-17k.parquet'
df = pd.read_parquet(out_path)

df["prompt_critic"] = df.apply(make_prompt_critic, axis=1)

df.to_parquet(out_path)
print(f"Saved {len(df)} rows to {out_path}")
df[["prompt", "prompt_critic"]].head(2)